# Deploy directly to Knowledge Bot project
# Add this at the top of render.yaml to specify the project
project: knowledge-bot

services:
  # Primary ChromaDB instance - needs persistent storage
  - type: web
    name: chroma-primary
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: standard  # $7/month - cheapest plan with disk support
    disk:
      name: chroma-primary-data
      mountPath: /chroma/chroma
      sizeGB: 10
    healthCheckPath: /api/v2/version
    envVars:
      - key: CHROMA_SERVER_HOST
        value: 0.0.0.0
      - key: CHROMA_SERVER_HTTP_PORT
        value: 8000
      - key: CHROMA_PERSIST_DIRECTORY
        value: /chroma/chroma
      - key: INSTANCE_ROLE
        value: primary
      - key: INSTANCE_PRIORITY
        value: 100
      # Resource monitoring for upgrade alerts
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: MEMORY_LIMIT_MB
        value: "1024"
      - key: RESOURCE_CHECK_INTERVAL
        value: "60"
      - key: DATABASE_URL
        value: postgresql://chroma_user:xqIF9T5U6LhySuSw86JqWYf7qtyGDXy8@dpg-d16mkandiees73db52u0-a.oregon-postgres.render.com/chroma_ha

  # Replica ChromaDB instance - needs persistent storage
  - type: web
    name: chroma-replica
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: standard  # $7/month - cheapest plan with disk support
    disk:
      name: chroma-replica-data
      mountPath: /chroma/chroma
      sizeGB: 10
    healthCheckPath: /api/v2/version
    envVars:
      - key: CHROMA_SERVER_HOST
        value: 0.0.0.0
      - key: CHROMA_SERVER_HTTP_PORT
        value: 8000
      - key: CHROMA_PERSIST_DIRECTORY
        value: /chroma/chroma
      - key: INSTANCE_ROLE
        value: replica
      - key: INSTANCE_PRIORITY
        value: 80
      # Resource monitoring for upgrade alerts
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: MEMORY_LIMIT_MB
        value: "1024"
      - key: RESOURCE_CHECK_INTERVAL
        value: "60"
      - key: DATABASE_URL
        value: postgresql://chroma_user:xqIF9T5U6LhySuSw86JqWYf7qtyGDXy8@dpg-d16mkandiees73db52u0-a.oregon-postgres.render.com/chroma_ha

  # Unified WAL Load Balancer - Enhanced sync + load balancing
  - type: web
    name: chroma-load-balancer
    env: docker
    dockerfilePath: ./Dockerfile.loadbalancer
    region: oregon
    plan: standard  # $7/month - cheapest plan with disk support
    healthCheckPath: /health
    envVars:
      - key: PRIMARY_URL
        value: https://chroma-primary.onrender.com
      - key: REPLICA_URL
        value: https://chroma-replica.onrender.com
      - key: CHECK_INTERVAL
        value: 30
      - key: FAILURE_THRESHOLD
        value: 3
      - key: LOAD_BALANCE_STRATEGY
        value: optimized_read_replica
      # Performance optimizations
      - key: MAX_CONCURRENT_REQUESTS
        value: 8
      - key: CONNECTION_POOL_SIZE
        value: 10
      - key: REQUEST_QUEUE_SIZE
        value: 50
      - key: REQUEST_TIMEOUT
        value: 15
      - key: CIRCUIT_BREAKER_TIMEOUT
        value: 30
      - key: READ_REPLICA_RATIO
        value: 0.8
      # Unified WAL System Configuration
      - key: DATABASE_URL
        value: postgresql://chroma_user:xqIF9T5U6LhySuSw86JqWYf7qtyGDXy8@dpg-d16mkandiees73db52u0-a.oregon-postgres.render.com/chroma_ha
      - key: WAL_ENABLED
        value: "true"
      - key: WAL_BATCH_SIZE
        value: 100
      - key: WAL_SYNC_INTERVAL
        value: 10
      - key: WAL_HIGH_VOLUME_BATCH_SIZE
        value: 200
      - key: WAL_MEMORY_THRESHOLD
        value: 80
      - key: WAL_CPU_THRESHOLD
        value: 80
      - key: WAL_DELETION_CONVERSION
        value: "true"
      - key: WAL_RETRY_ATTEMPTS
        value: 3
      - key: WAL_RETRY_DELAY
        value: 5
      - key: WAL_PERSISTENCE_SCHEMA
        value: "true"
      # Slack Integration
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: SLACK_ALERTS_ENABLED
        value: "true"
      - key: SLACK_UPGRADE_ALERTS
        value: "true"

  # Monitor worker - workers don't support free tier
  - type: worker
    name: chroma-monitor
    env: docker
    dockerfilePath: ./Dockerfile.monitor
    region: oregon
    plan: standard  # $7/month - workers don't have free tier
    envVars:
      - key: PRIMARY_URL
        value: https://chroma-primary.onrender.com
      - key: REPLICA_URL
        value: https://chroma-replica.onrender.com
      - key: LOAD_BALANCER_URL
        value: https://chroma-load-balancer.onrender.com
      - key: CHECK_INTERVAL
        value: 30
      - key: FAILURE_THRESHOLD
        value: 3
      # Resource monitoring thresholds
      - key: MEMORY_WARNING_THRESHOLD
        value: 80
      - key: MEMORY_CRITICAL_THRESHOLD
        value: 95
      - key: CPU_WARNING_THRESHOLD
        value: 80
      - key: CPU_CRITICAL_THRESHOLD
        value: 95
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: DATABASE_URL
        value: postgresql://chroma_user:xqIF9T5U6LhySuSw86JqWYf7qtyGDXy8@dpg-d16mkandiees73db52u0-a.oregon-postgres.render.com/chroma_ha

# Note: Using direct DATABASE_URL connections instead of Render database references
# This provides more reliable access to the PostgreSQL database