# Deploy directly to Knowledge Bot project
# Add this at the top of render.yaml to specify the project
project: knowledge-bot

services:
  # Primary ChromaDB instance - needs persistent storage
  - type: web
    name: chroma-primary
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: standard  # $7/month - cheapest plan with disk support
    disk:
      name: chroma-primary-data
      mountPath: /chroma/chroma
      sizeGB: 10
    healthCheckPath: /api/v2/version
    envVars:
      - key: CHROMA_SERVER_HOST
        value: 0.0.0.0
      - key: CHROMA_SERVER_HTTP_PORT
        value: 8000
      - key: CHROMA_PERSIST_DIRECTORY
        value: /chroma/chroma
      - key: INSTANCE_ROLE
        value: primary
      - key: INSTANCE_PRIORITY
        value: 100

  # Replica ChromaDB instance - needs persistent storage
  - type: web
    name: chroma-replica
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: standard  # $7/month - cheapest plan with disk support
    disk:
      name: chroma-replica-data
      mountPath: /chroma/chroma
      sizeGB: 10
    healthCheckPath: /api/v2/version
    envVars:
      - key: CHROMA_SERVER_HOST
        value: 0.0.0.0
      - key: CHROMA_SERVER_HTTP_PORT
        value: 8000
      - key: CHROMA_PERSIST_DIRECTORY
        value: /chroma/chroma
      - key: INSTANCE_ROLE
        value: replica
      - key: INSTANCE_PRIORITY
        value: 80

  # Load Balancer - no storage needed, can be free
  - type: web
    name: chroma-load-balancer
    env: docker
    dockerfilePath: ./Dockerfile.loadbalancer
    region: oregon
    plan: starter  # Free plan - no storage needed
    healthCheckPath: /health
    envVars:
      - key: PRIMARY_URL
        value: https://chroma-primary.onrender.com
      - key: REPLICA_URL
        value: https://chroma-replica.onrender.com
      - key: CHECK_INTERVAL
        value: 30
      - key: FAILURE_THRESHOLD
        value: 3
      - key: LOAD_BALANCE_STRATEGY
        value: write_primary
      - key: SLACK_WEBHOOK_URL
        sync: false

  # Monitor worker - workers don't support free tier
  - type: worker
    name: chroma-monitor
    env: docker
    dockerfilePath: ./Dockerfile.monitor
    region: oregon
    plan: standard  # $7/month - workers don't have free tier
    envVars:
      - key: PRIMARY_URL
        value: https://chroma-primary.onrender.com
      - key: REPLICA_URL
        value: https://chroma-replica.onrender.com
      - key: LOAD_BALANCER_URL
        value: https://chroma-load-balancer.onrender.com
      - key: CHECK_INTERVAL
        value: 30
      - key: FAILURE_THRESHOLD
        value: 3
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: chroma-metadata
          property: connectionString

  # Sync worker - workers don't support free tier
  - type: worker
    name: chroma-sync
    env: docker
    dockerfilePath: ./Dockerfile.sync
    region: oregon
    plan: standard  # $7/month - workers don't have free tier
    envVars:
      - key: PRIMARY_URL
        value: https://chroma-primary.onrender.com
      - key: REPLICA_URL
        value: https://chroma-replica.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: chroma-metadata
          property: connectionString
      - key: SYNC_INTERVAL
        value: 300
      - key: MAX_MEMORY_MB
        value: "400"
      - key: MAX_WORKERS
        value: "2"
      - key: SYNC_DISTRIBUTED
        value: "false"
      - key: SYNC_COORDINATOR
        value: "false"
      - key: SYNC_CHUNK_SIZE
        value: "1000"
      - key: SLACK_WEBHOOK_URL
        sync: false

databases:
  # Optional: PostgreSQL for storing failover state and metrics
  - name: chroma-metadata
    databaseName: chroma_ha
    user: chroma_user
    region: oregon
    plan: free  # Free PostgreSQL 