services:
  - type: web
    name: chroma
    env: docker
    repo: https://github.com/latris-io/knowledge-bot-chroma
    branch: main
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000

